name: Windows CMake Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout código fuente
      uses: actions/checkout@v3

    - name: Configurar entorno de Visual Studio
      uses: ilammy/msvc-dev-cmd@v1

    - name: Crear carpeta build
      run: mkdir build

    - name: Configurar CMake
      working-directory: build
      run: cmake .. -G "Visual Studio 17 2022" -A x64

    - name: Compilar proyecto
      working-directory: build
      run: cmake --build . --config Debug

    - name: Ejecutar pruebas
      working-directory: build
      run: ctest -C Debug --output-on-failure
